# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_auto_20171118_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='military',
            name='name',
        ),
    ]
