# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economy',
            name='name',
        ),
        migrations.AddField(
            model_name='economy',
            name='quanta',
            field=models.IntegerField(default=0, help_text='cash'),
            preserve_default=False,
        ),
    ]
