# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_remove_military_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humans',
            name='name',
        ),
    ]
