# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.TextField(default=1, help_text='Enter how the fullfiled job will be rewarded', max_length=1000),
            preserve_default=False,
        ),
    ]
