# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('jtype', models.ManyToManyField(help_text='Select the type of job', to='jobboard.Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jtype',
        ),
        migrations.AlterModelOptions(
            name='jobinstance',
            options={},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='jobinstance',
            old_name='borrower',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='jobinstance',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='jobinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='position',
            field=models.CharField(default=1, help_text='Set coordinates', max_length=1000, verbose_name='Coordinates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='salary',
            field=models.TextField(default=1, help_text='Enter how the fullfiled job will be rewarded', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='summary',
            field=models.TextField(default=1, help_text='Enter a brief description of the job', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobboard.JobTemplate'),
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Open'), ('f', 'filled')], default='m', help_text='Job availability', max_length=1),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
