# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobboard', '0003_auto_20171125_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jtype', models.ManyToManyField(help_text='Select the type of job', to='jobboard.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Enter a brief description of the job', max_length=1000)),
                ('salary', models.TextField(help_text='Enter how the fullfiled job will be rewarded', max_length=1000)),
                ('position', models.CharField(help_text='Set coordinates', max_length=1000, verbose_name='Location')),
                ('status', models.CharField(blank=True, choices=[('o', 'Open'), ('f', 'filled')], default='m', help_text='Job availability', max_length=1)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobboard.Operation')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobinstance',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='jobinstance',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='jtype',
        ),
        migrations.DeleteModel(
            name='JobInstance',
        ),
        migrations.DeleteModel(
            name='JobTemplate',
        ),
    ]
