# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_auto_20171128_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='taskList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobboard.Task'),
        ),
    ]
